<h1><b>Demand Forecasting to Accomodate all Players </h1><br>

<h3><b>Introduction:</h3> <br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This report is based on data collected by a research group in Computer Science from the University of British Columbia. This data was collected through a video game called Minecraft, with the purpose of figuring out how people play video games by recording the players' actions. Minecraft is a blocky video game that offers a variety of playstyles and challenges that can satisfy the experiences of a wide range of players. 
<br> <br>
During the making of this Science project, a concern was if the research group had enough resources to handle all the players they attracted. These players can play at any times throughout the day, as long as spots are available. To help address their concern, a question from the project lead, Frank Wood, that we will be answering is: <b>"We are interested in demand forecasting, namely, what time windows are most likely to have large number of simultaneous players. This is because we need to ensure that the number of licenses on hand is sufficiently large to accommodate all parallel players with high probability."</b>
<br><br>
To answer this question, we were given two datasets from the research group that we will be using. The first dataset is named, "players." The players dataset has 9 variables with 196 observations. The players dataset stores information that is about the user who is playing. The second dataset is named, "sessions." The sessions dataset has 5 variables with 1535 observations. The sessions dataset stores information that is about the user's play time. Illustrated with the tables below are the variables and a description of what the variables are, for each respective dataset. We will be focusing on the sessions dataset as we are more interested in finding what time window(s) there are the most amount of players playing.

<br>
<table>
<tr>
    <th>Players Dataset Variables:</th>
</tr>
<tr>
    <th>experience:</th>
    <td>Player's experience with Minecraft. </td>
</tr>
<tr>
    <th>subscribe:</th>
    <td>If the player is subscribed with their email. </td>
</tr>
<tr>
    <th>hashEmail:</th>
    <td>Encryption code used to identify specific player. </td>
</tr>
<tr>
    <th>played_hours:</th>
    <td>Player's total time in hours. </td>
</tr>
<tr>
    <th>name:</th>
    <td>Player's fake name. </td>
</tr>
<tr>
    <th>gender:</th>
    <td>Player's gender. </td>
</tr>
<tr>
    <th>age:</th>
    <td>Player's age. </td>
</tr>
<tr>
    <th>individualid:</th>
    <td>Player's individual ID. </td>
</tr>
<tr>
    <th>organizationName:</th>
    <td>Player's organization name. </td>
</tr>
</table>

<br><br>

<table>
<tr>
    <th>Sessions Dataset Variables:</th>
</tr>
<tr>
    <th>hashEmail:</th>
    <td>Encryption code used to identify specific player. </td>
</tr>
<tr>
    <th>start_time:</th>
    <td>When the player starts playing.</td>
</tr>
<tr>
    <th>end_time:</th>
    <td>When the player stops playing.</td>
</tr>
<tr>
    <th>original_start_time:</th>
    <td>When the player starts playing.</td>
</tr>
<tr>
    <th>original_end_time:</th>
    <td> When the player stops playing.</td>
</tr>
</table>

<h3><b>Methods & Results:</h3>

In [17]:
import pandas as pd

players_data  = pd.read_csv('data/players.csv')
sessions_data = pd.read_csv('data/sessions.csv')

players_data.drop(columns = ["subscribe", "individualId", "organizationName", "hashedEmail"]) # RL - Unsure if this is needed as we only need to look at the sessions dataset
sessions_data.drop(columns = ["hashedEmail"])  #, "original_start_time", "original_end_time" # RL - We can also probably get rid of original_start_time and original_end_time

,start_time,end_time,original_start_time,original_end_time
0,30/06/2024 18:12,30/06/2024 18:24,1.719770e+12,1.719770e+12
1,17/06/2024 23:33,17/06/2024 23:46,1.718670e+12,1.718670e+12
2,25/07/2024 17:34,25/07/2024 17:57,1.721930e+12,1.721930e+12
3,25/07/2024 03:22,25/07/2024 03:58,1.721880e+12,1.721880e+12
4,25/05/2024 16:01,25/05/2024 16:12,1.716650e+12,1.716650e+12
...,...,...,...,...
1530,10/05/2024 23:01,10/05/2024 23:07,1.715380e+12,1.715380e+12
1531,01/07/2024 04:08,01/07/2024 04:19,1.719810e+12,1.719810e+12
1532,28/07/2024 15:36,28/07/2024 15:57,1.722180e+12,1.722180e+12
1533,25/07/2024 06:15,25/07/2024 06:22,1.721890e+12,1.721890e+12
1534,20/05/2024 02:26,20/05/2024 02:45,1.716170e+12,1.716170e+12